### ISSUE TITLE
Connect, "invalid URL, scheme is not http"

### ISSUE THREAD

**Issue by Blobadoodle** [Adrian8115/discord-webhook2#2]
All examples do not work, and instead I am getting a client::legacy::Error(Connect, "invalid URL, scheme is not http") }) error.

I have no clue why, I have just copy pasted the example code to test it and made no modifications. (apart from putting my URL in).

```rs
use discord_webhook2::message::Message;
use discord_webhook2::webhook::DiscordWebhook;

#[tokio::main]
async fn main() {
    let webhook = DiscordWebhook::new("<my url>").unwrap();

    webhook
        .send(&Message::new(|message| message.content("Hello World!")))
        .await
        .unwrap();
}
```

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\webhook-test.exe`
thread 'main' panicked at src\main.rs:11:10:
called `Result::unwrap()` on an `Err` value: ReqwestError(reqwest::Error { kind: Request, url: "<my url>", source: hyper_util::client::legacy::Error(Connect, "invalid URL, scheme is not http") })
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:597
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\panicking.rs:72
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\result.rs:1652
   3: enum2$<core::result::Result<discord_webhook2::id::DiscordID,enum2$<discord_webhook2::error::DiscordWebhookError> > >::unwrap<discord_webhook2::id::DiscordID,enum2$<discord_webhook2::error::DiscordWebhookError> >
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\result.rs:1077
   4: webhook_test::main::async_block$0
             at .\src\main.rs:8
   5: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<webhook_test::main::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\park.rs:281
   6: tokio::runtime::coop::with_budget
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\coop.rs:107
   7: tokio::runtime::coop::budget
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\coop.rs:73
   8: tokio::runtime::park::CachedParkThread::block_on<enum2$<webhook_test::main::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\park.rs:281
   9: tokio::runtime::context::blocking::BlockingRegionGuard::block_on<enum2$<webhook_test::main::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\context\blocking.rs:66
  10: tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<enum2$<webhook_test::main::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\scheduler\multi_thread\mod.rs:87
  11: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<enum2$<webhook_test::main::async_block_env$0> >,tuple$<> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\context\runtime.rs:65
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<webhook_test::main::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\scheduler\multi_thread\mod.rs:86
  13: tokio::runtime::runtime::Runtime::block_on_inner<enum2$<webhook_test::main::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\runtime.rs:363
  14: tokio::runtime::runtime::Runtime::block_on<enum2$<webhook_test::main::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.40.0\src\runtime\runtime.rs:335
  15: webhook_test::main
             at .\src\main.rs:8
  16: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\webhook-test.exe` (exit code: 101)
```

```
rustc 1.74.1 (a28077b28 2023-12-04)
cargo 1.74.1 (ecb9851af 2023-10-18)

discord-webhook2 = "0.4.0"
tokio = "1.40.0"
```

**Comment by Blobadoodle** [comment]
My bad, enabling the "rustls-tls" feature fixed this.

**Comment by theaddonn** [comment]
heya thanks for opening the issue, I will still take a look at it ^^

**Comment by theaddonn** [comment]
This is indeed an issue and I will fix it tomorrow

**Comment by theaddonn** [comment]
this should be fixed in https://github.com/theaddonn/discord-webhook2/commit/427de010dad8df21f16fb6fc977314cfa43a85b7
